### ISSUE TITLE
Unknown data location

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/ansp-para#1]
The source for the data is unknown. See [https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=236](https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=236)

**Comment by seltmann** [comment]
Data location unknown as of June 24, 2021
Poelen, Jorrit H., Seltmann, Katja C., & Campbell, Mariel. (2021). Terrestrial Parasite Tracker indexed biotic interactions and review summary (Version 0.4) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.5029617

**Comment by seltmann** [comment]
From a conversation with Kat. Data from ANSP will be published via the field museum IPT because it is Field Museum specimens. They are planning to provide ANSP specimens but do not know where they will be published at this time.

**Comment by jhpoelen** [comment]
data location configured and first data review was generated. See attached screenshot.

![image](https://github.com/globalbioticinteractions/ansp-para/assets/1084872/675cd9d0-f51b-4a0b-b4d7-a9615e345140)
